# https://remarkablemark.org/blog/2023/02/18/how-to-run-react-native-detox-tests-on-github-actions/
name: Detox tests for iOS

on: [push]

jobs:
  detox-ios:
    runs-on: macos-13

    steps:
      # - run: echo ${{ github.workspace }}
      # - run: pwd

      # - name: create Google Services File
      #   env:
      #     DATA: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
      #   run: |
      #     echo $DATA | base64 --decode > ${{ github.workspace }}/GoogleService-Info.plist

      # - run: chmod 777 ${{ github.workspace }}/GoogleService-Info.plist
      # - run: find $PWD -type f | grep "GoogleService"

      - name: checkout
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Install Expo
        run: yarn add expo

      - name: Install macOS dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew tap wix/brew
          brew install applesimutils

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Cache CocoaPods
        id: cache-cocoapods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.14.3

      - name: Prebuild
        env:
          GOOGLE_SERVICES_INFO_PLIST: ${{ github.workspace }}/e2e/mock-google-service-info.plist
        run: yarn prebuild:test:ios

      - name: Install CocoaPods
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: cd ios ; rm .xcode.env.local ; pod install ; cd -

      - name: Detox rebuild framework cache
        run: yarn detox rebuild-framework-cache

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Detox build
        env:
          EXPO_PUBLIC_DETOX_MOCKED: true
          EXPO_PUBLIC_AUTH_HOST: https://auth.stage.graasp.org
          EXPO_PUBLIC_API_HOST: https://api.stage.graasp.org
          EXPO_PUBLIC_TEST_REFRESH_TOKEN: ${{ secrets.EXPO_PUBLIC_TEST_REFRESH_TOKEN }}
          RN_SRC_EXT: e2e.tsx
        run: yarn build:test:ios

      - name: Detox test
        env:
          EXPO_PUBLIC_DETOX_MOCKED: true
          EXPO_PUBLIC_AUTH_HOST: https://auth.stage.graasp.org
          EXPO_PUBLIC_API_HOST: https://api.stage.graasp.org
          EXPO_PUBLIC_TEST_REFRESH_TOKEN: ${{ secrets.EXPO_PUBLIC_TEST_REFRESH_TOKEN }}
          RN_SRC_EXT: e2e.tsx
        run: yarn test:ios:ci --cleanup --headless --record-logs all

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts
